services:
  db:
    image: postgres:16.3
#    restart: always
    environment:
      - POSTGRES_USER=manzi
      - POSTGRES_PASSWORD=manzi
    ports:
      - '5432:5432'
    volumes: 
      - ./data-files:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
volumes:
  db:
    driver: local
